name: CI

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: "3.x"
          architecture: "x64"
      - name: Convert json
        run: python ./bin/convert_json.py
      - name: Update collections
        run: ./bin/update_collections.sh
        env:
          POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}
