name: CI

on:
  pull_request:
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: jumpyoshim/postman-integration@master
      - name: Update collections
        run: ./bin/update_collections.sh
